### ISSUE TITLE
Single end mode - with error exit code 1, not annotating count table with GTF or completing multiqc

### ISSUE THREAD

**Issue by methylnick** [MonashBioinformaticsPlatform/RNAsik-pipe#11]
There seems to be a little bug here, with an exit value of 1. Does not seem the count tables are annotated with the gene names, biotype or accession.

MultiQC was not run even though it was requested.

Log:
http://bioinformatics.erc.monash.edu/home/nick-wong/projects/nick.wong/bgiSeq/RNAsik.bds.20171219_110415_253.report.html

**Comment by serine** [comment]
@methylnick I think I might have fixed that issues in 1.4.9 release. However it is not always possible to provide "clean", what I call degust ready, counts files, because annotation file may not be fully supported or annotation file simply doesn't have the right information in it. 

I've made bunch of improvement in 1.4.9, one important thing for this issue is that now `RNAsik` won't fail if counts file "cleaning" task had failed. Actual `featureCounts` shouldn't fail, if it does please report again as a separate issue, but "cleaning up" task that generated `-withNames.txt` and `-withNames-proteinCoding.txt` files may fail depending on your annotation file. If that happens that's annoying, but you still should have your original counts files from `featureCounts` and those are still usable with degust just less informative and contain extra (unwanted) columns. 

I'm in the process of documenting how to use bunch of python script that come with `RNAsik` to obtain those "clean" counts file. In the case if "cleaning up" step failed during `RNAsik` run, user could still try to use those script to "clean up" manually.

Thanks for the issue, will close this for now. Feel free to reopen it if you feel like it hasn't been resolved

Cheers
